notifico/views/projects/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""__init__.py

Project related views, such as project creation and details.
"""
from functools import wraps

from flask import (
    Blueprint,
    render_template,
    g,
    redirect,
    url_for,
    abort,
    request
)
from flask.ext import wtf

from notifico import db, user_required
from notifico.models import User, Project, Hook, Channel
from notifico.services.hooks import HookService

projects = Blueprint('projects', __name__, template_folder='templates')


class ProjectDetailsForm(wtf.Form):
    name = wtf.TextField('Project Name', validators=[
        wtf.Required(),
        wtf.Length(1, 50),
        wtf.Regexp(r'^[a-zA-Z0-9_\-\.]*$', message=(
            'Project name must only contain a to z, 0 to 9, dashes'
            ' and underscores.'
        ))
    ])
    public = wtf.BooleanField('Public', validators=[
    ], default=True)
    website = wtf.TextField('Project URL', validators=[
        wtf.Optional(),
        wtf.Length(max=1024),
        wtf.validators.URL()
    ])


class HookDetailsForm(wtf.Form):
    service_id = wtf.SelectField('Service', validators=[
        wtf.Required()
    ], coerce=int)


class PasswordConfirmForm(wtf.Form):
    password = wtf.PasswordField('Password', validators=[
        wtf.Required()
    ])

    def validate_password(form, field):
        if not User.login(g.user.username, field.data):
            raise wtf.ValidationError('Your password is incorrect.')


class ChannelDetailsForm(wtf.Form):
    channel = wtf.TextField('Channel', validators=[
        wtf.Required(),
        wtf.Length(min=1, max=80)
    ])
    host = wtf.TextField('Host', validators=[
        wtf.Required(),
        wtf.Length(min=1, max=255)
    ], default='chat.freenode.net')
    port = wtf.IntegerField('Port', validators=[
        wtf.NumberRange(1024, 66552)
    ], default=6667)
    ssl = wtf.BooleanField('Use SSL', default=False)
    public = wtf.BooleanField('Public', default=True, description=(
        'Allow others to see that this channel exists.'
    ))


def project_action(f):
    """
    A decorator for views which act on a project. The function
    should take two kwargs, `u` (the username) and `p` (the project name),
    which will be resolved and replaced, or a 404 will be raised if either
    could not be found.
    """
    @wraps(f)
    def _wrapped(*args, **kwargs):
        u = User.by_username(kwargs.pop('u'))
        if not u:
            # No such user exists.
            return abort(404)

        p = Project.by_name_and_owner(kwargs.pop('p'), u)
        if not p:
            # Project doesn't exist (404 Not Found)
            return abort(404)

        kwargs['p'] = p
        kwargs['u'] = u

        return f(*args, **kwargs)
    return _wrapped


@projects.route('/<u>/')
def dashboard(u):
    """
    Display an overview of all the user's projects with summary
    statistics.
    """
    u = User.by_username(u)
    if not u:
        # No such user exists.
        return abort(404)

    is_owner = (g.user and g.user.id == u.id)

    # Get all projects by decending creation date.
    projects = (
        u.projects
        .order_by(False)
        .order_by(Project.created.desc())
    )
    if not is_owner:
        # If this isn't the users own page, only
        # display public projects.
        projects = projects.filter_by(public=True)

    return render_template('dashboard.html',
        user=u,
        is_owner=is_owner,
        projects=projects,
        page_title='Notifico! - {u.username}\'s Projects'.format(
            u=u
        )
    )


@projects.route('/new', methods=['GET', 'POST'])
@user_required
def new():
    """
    Create a new project.
    """
    form = ProjectDetailsForm()
    if form.validate_on_submit():
        p = Project.by_name_and_owner(form.name.data, g.user)
        if p:
            form.name.errors = [
                wtf.ValidationError('Project name must be unique.')
            ]
        else:
            p = Project.new(
                form.name.data,
                public=form.public.data,
                website=form.website.data
            )
            p.full_name = '{0}/{1}'.format(g.user.username, p.name)
            g.user.projects.append(p)
            db.session.add(p)

            if p.public:
                # New public projects get added to #commits by default.
                c = Channel.new(
                    '#commits',
                    'chat.freenode.net',
                    6667,
                    ssl=False,
                    public=True
                )
                p.channels.append(c)

            db.session.commit()

            return redirect(url_for('.details', u=g.user.username, p=p.name))

    return render_template('new_project.html', form=form)


@projects.route('/<u>/<p>/edit', methods=['GET', 'POST'])
@user_required
@project_action
def edit_project(u, p):
    """
    Edit an existing project.
    """
    if p.owner.id != g.user.id:
        # Project isn't public and the viewer isn't the project owner.
        # (403 Forbidden)
        return abort(403)

    form = ProjectDetailsForm(obj=p)
    if form.validate_on_submit():
        old_p = Project.by_name_and_owner(form.name.data, g.user)
        if old_p and old_p.id != p.id:
            form.name.errors = [
                wtf.ValidationError('Project name must be unique.')
            ]
        else:
            p.name = form.name.data
            p.website = form.website.data
            p.public = form.public.data
            p.full_name = '{0}/{1}'.format(g.user.username, p.name)
            db.session.commit()
            return redirect(url_for('.dashboard', u=u.username))

    return render_template('edit_project.html',
        project=p,
        form=form
    )


@projects.route('/<u>/<p>/delete', methods=['GET', 'POST'])
@user_required
@project_action
def delete_project(u, p):
    """
    Delete an existing project.
    """
    if p.owner.id != g.user.id:
        # Project isn't public and the viewer isn't the project owner.
        # (403 Forbidden)
        return abort(403)

    if request.method == 'POST' and request.form.get('do') == 'd':
        db.session.delete(p)
        db.session.commit()
        return redirect(url_for('.dashboard', u=u.username))

    return render_template('delete_project.html', project=p)


@projects.route('/<u>/<p>')
@project_action
def details(u, p):
    """
    Show the details for an existing project.
    """
    if not p.can_see(g.user):
        return redirect(url_for('public.landing'))

    can_modify = p.can_modify(g.user)

    visible_channels = p.channels
    if not can_modify:
        visible_channels = visible_channels.filter_by(public=True)

    return render_template(
        'project_details.html',
        project=p,
        user=u,
        visible_channels=visible_channels,
        can_modify=can_modify,
        page_title='Notifico! - {u.username}/{p.name}'.format(
            u=u,
            p=p
        )
    )


@projects.route('/<u>/<p>/hook/new', defaults={'sid': 10}, methods=[
    'GET', 'POST'])
@projects.route('/<u>/<p>/hook/new/<int:sid>', methods=['GET', 'POST'])
@user_required
@project_action
def new_hook(u, p, sid):
    if p.owner.id != g.user.id:
        # Project isn't public and the viewer isn't the project owner.
        # (403 Forbidden)
        return abort(403)

    hook = HookService.services.get(sid)
    form = hook.form()
    if form:
        form = form()

    if form and hook.validate(form, request):
        h = Hook.new(sid, config=hook.pack_form(form))
        p.hooks.append(h)
        db.session.add(h)
        db.session.commit()
        return redirect(url_for('.details', p=p.name, u=u.username))
    elif form is None and request.method == 'POST':
        h = Hook.new(sid)
        p.hooks.append(h)
        db.session.add(h)
        db.session.commit()
        return redirect(url_for('.details', p=p.name, u=u.username))

    return render_template('new_hook.html',
        project=p,
        services=HookService.services,
        service=hook,
        form=form
    )


@projects.route('/<u>/<p>/hook/edit/<int:hid>', methods=['GET', 'POST'])
@user_required
@project_action
def edit_hook(u, p, hid):
    if p.owner.id != g.user.id:
        return abort(403)

    h = Hook.query.get(hid)
    if h is None:
        # You can't edit a hook that doesn't exist!
        return abort(404)

    if h.project.owner.id != g.user.id:
        # You can't edit a hook that isn't yours!
        return abort(403)

    hook_service = h.hook()
    form = hook_service.form()
    if form:
        form = form()

    if form and hook_service.validate(form, request):
        h.config = hook_service.pack_form(form)
        db.session.add(h)
        db.session.commit()
        return redirect(url_for('.details', p=p.name, u=u.username))
    elif form is None and request.method == 'POST':
        db.session.add(h)
        db.session.commit()
        return redirect(url_for('.details', p=p.name, u=u.username))
    elif form:
        hook_service.load_form(form, h.config)

    return render_template('edit_hook.html',
        project=p,
        services=HookService.services,
        service=hook_service,
        form=form
    )


@projects.route('/h/<int:pid>/<key>', methods=['GET', 'POST'])
def hook_receive(pid, key):
    h = Hook.query.filter_by(key=key, project_id=pid).first()
    if not h or not h.project:
        # The hook being pushed to doesn't exist, has been deleted,
        # or is a leftover from a project cull (which destroyed the project
        # but not the hooks associated with it).
        return abort(404)

    # Increment the hooks message_count....
    Hook.query.filter_by(id=h.id).update({
        Hook.message_count: Hook.message_count + 1
    })
    # ... and the project-wide message_count.
    Project.query.filter_by(id=h.project.id).update({
        Project.message_count: Project.message_count + 1
    })

notifico/templates/body.html
{% macro repo_link(project) %}
{% if not project.public %}
<i class="icon-lock"></i>
{% endif %}
<a href="{{ url_for('projects.dashboard', u=project.owner.username) }}">
  {{ project.owner.username }}
</a><span class="muted">/</span><a href="{{ url_for('projects.details', u=project.owner.username, p=project.name) }}">
  {{ project.name }}
</a>
{% endmacro %}
{% macro active(end) %}
{% if request.endpoint.startswith(end) %}active{% endif %}
{% endmacro %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{{ page_title|default('Notifico!') }}</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="/css/bootstrap.css?v=3" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
    {% block style %}
    {% endblock style %}
    <link href="/css/bootstrap-responsive.min.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    {% if config.GOOGLE %}
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', '{{ config.GOOGLE }}']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
    {% endif %}
  </head>

  <body>
    <div class="wrapper">
      <div class="nav-container">
        <div class="container">
          <div class="navbar nav-top">
            <div class="navbar-inner">
              <a class="brand" href="/">Notifico</a>
              <ul class="nav pull-right">
                <li class="{{ active('public.landing') }}">
                  <a href="/"><i class="icon-home"></i> Home</a>
                </li>
                {% if g.user %}
                <li class="{{ active('projects.') }}">
                  <a href="{{ url_for('projects.dashboard', u=g.user.username) }}">
                    <i class="icon-th"></i> Projects
                  </a>
                </li>
                <!-- User settings and actions  -->
                <li class="dropdown {{ active('account.') }}">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      <i class="icon-user"></i> {{ g.user.username }} <i class="icon-angle-down"></i> 
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                      <a href="{{ url_for('account.settings') }}">
                        <i class="icon-cog"></i> Settings
                      </a>
                    </li>
                    <li>
                      <a href="{{ url_for('account.tokens') }}">
                        <i class="icon-key"></i> OAuth Tokens
                      </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="{{ url_for('account.logout') }}">
                            <i class="icon-signout"></i> Logout
                        </a>
                    </li>
                  </ul>
                </li>
                {% else %}
                <li>
                  <a href="{{ url_for('account.login') }}">
                    <i class="icon-signin"></i> Login
                  </a>
                </li>
                <li>
                  <a href="{{ url_for('account.register') }}">
                    <i class="icon-plus"></i> Register
                  </a>
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="container content">
        {% block content %}
        {% endblock content %}
      </div>
    </div>
    <div class="footer">
      <div class="container">
        <div class="row-fluid">
          <div class="span12 footer-copyright">
            Copyright &copy; <span class="current_year">2013</span> Tyler Kennedy
          </div>
        </div>
      </div>
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="/js/jquery.min.js"><\/script>')</script>
    <script src="/js/bootstrap.js"></script>
    {% block script %}
    <script>
      $(function(){
          // Focus on the username box, but only if
          // the user hasn't already focused on something else.
          if($(document.activeElement).is('body')) {
              $('.focus').focus();
          }

          $('.current_year').text(new Date().getFullYear());
      });
    </script>
    {% endblock %}
  </body>
</html>